version: "3.1"
services:
   jenkins:
     image: jenkins/jenkins:2.332.2-lts
     container_name: jenkins
     restart: always
     ports:
       - 8080:8080
       - 50000:50000
     volumes:
       - ./data/:/var/jenkins_home/
